//CRT
#include "core_crt/stdint.h"
#include "core_crt/stdarg.h"
#include "core_crt/stdlib.h"
#include "core_crt/stdio.h"
#include "core_crt/wchar.h"
#include "core_crt/string.h"
#include "core_crt/ctype.h"

#include "default_handlers.c"
#include "event.c"
#include "interpreter.c"
#include "io.c"
#include "mutex.c"
#include "namespace.c"
#include "notify.c"
#include "opcodes.c"
#include "opregion.c"
#include "osi.c"
#include "registers.c"
#include "resources.c"
#include "shareable.c"
#include "sleep.c"
#include "stdlib.c"
#include "tables.c"
#include "types.c"
#include "uacpi.c"
#include "utilities.c"
