/* automatically generated by rust-bindgen 0.59.2 */

pub const SystemCallResult_Success: SystemCallResult = 0;
pub const SystemCallResult_InvalidPointer: SystemCallResult = 1;
pub const SystemCallResult_InvalidHandle: SystemCallResult = 2;
pub const SystemCallResult_InvalidObject: SystemCallResult = 3;
pub const SystemCallResult_BrokenPipe: SystemCallResult = 4;
pub const SystemCallResult_Failed: SystemCallResult = 5;
pub const SystemCallResult_NotImplemented: SystemCallResult = 6;
pub type SystemCallResult = c_types::c_int;
extern "C" {
    pub fn DebugPrint(s: *const c_types::c_char) -> SystemCallResult;
}
extern "C" {
    pub fn printf(_Format: *const c_types::c_char) -> c_types::c_int;
}
