/* automatically generated by rust-bindgen 0.59.2 */

pub const SEEK_CUR: u32 = 1;
pub const SEEK_END: u32 = 2;
pub const SEEK_SET: u32 = 0;
pub const stdin: u32 = 0;
pub const stdout: u32 = 1;
pub const stderr: u32 = 2;
pub const BUFSIZ: u32 = 512;
pub const EOF: i32 = -1;
pub type FILE = c_types::c_void;
extern "C" {
    pub fn fopen(_FileName: *const c_types::c_char, _Mode: *const c_types::c_char) -> *mut FILE;
}
extern "C" {
    pub fn fread(
        _Buffer: *mut c_types::c_void,
        _ElementSize: size_t,
        _ElementCount: size_t,
        _Stream: *mut FILE,
    ) -> size_t;
}
extern "C" {
    pub fn fwrite(
        _Buffer: *const c_types::c_void,
        _ElementSize: size_t,
        _ElementCount: size_t,
        _Stream: *mut FILE,
    ) -> size_t;
}
extern "C" {
    pub fn fseek(
        _Stream: *mut FILE,
        _Offset: c_types::c_long,
        _Origin: c_types::c_int,
    ) -> c_types::c_int;
}
extern "C" {
    pub fn ftell(_Stream: *mut FILE) -> c_types::c_int;
}
extern "C" {
    pub fn fclose(_Stream: *mut FILE) -> c_types::c_int;
}
extern "C" {
    pub fn fprintf(_Stream: *mut FILE, _Format: *const c_types::c_char, ...) -> c_types::c_int;
}
extern "C" {
    pub fn rename(
        _OldFileName: *const c_types::c_char,
        _NewFileName: *const c_types::c_char,
    ) -> c_types::c_int;
}
extern "C" {
    pub fn remove(_FileName: *const c_types::c_char) -> c_types::c_int;
}
extern "C" {
    pub fn printf(_Format: *const c_types::c_char, ...) -> c_types::c_int;
}
